# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speed', '0002_car_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speed.Container'),
        ),
    ]
